# Generated by Django 4.0.3 on 2022-03-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorite',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
