# Generated by Django 4.0.3 on 2022-03-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_collection', '0004_artist_album_the_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='the_artist',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music_collection.artist'),
        ),
    ]
